@include('components.card_expand.down.event')
@include('components.card_expand.down.podcast')
@include('components.card_expand.down.product')
@include('components.card_expand.down.video')
@include('components.card_expand.down.blog')